title: Practice
description: This is to learn Github pages. <ul><a href="http://hannahlee345.github.io/about.html">About</a> 
logo: assets/img/coffee.jpg
show_downloads: false
google_analystics:
theme: jekyll-theme-minimal
