title: Practice
description: This is to learn Github pages. <ul><a href="http://HANNAHLEE345.github.io/About/">About</a></ul> <ul><a href="http://HANNAHLEE345.github.io/Venue/">Venue</a></ul> <ul><a href="http://HANNAHLEE345.github.io/Programme/">Programme</a></ul> <ul><a href="http://HANNAHLEE345.github.io/Authors/">Authors</a></ul> <ul><a href="http://HANNAHLEE345.github.io/Sponsor/">Sponsor</a></ul> <ul><a href="http://HANNAHLEE345.github.io/Registration/">Registration</a></ul>
logo: assets/img/coffee.jpg
show_downloads: false
google_analystics:
theme: jekyll-theme-minimal
