title: Practice
description: <b>About</b><nul><li><a href="https://github.com/HANNAHLEE345/HANNAHLEE345.github.io/blob/main/About.md"></a>. 
logo: assets/img/coffee.jpg
show_downloads: false
google_analystics:
theme: jekyll-theme-minimal
